package com.example.util

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.widget.Toast
import com.example.model.MarketPrediction

object ShareHelper {

    fun generateWhatsAppFormattedText(prediction: MarketPrediction, formulaName: String): String {
        val otcSpaced = prediction.otcList.joinToString(" - ") { it.toString() }
        val superJodisText = if (prediction.superJodiList.isNotEmpty()) {
            prediction.superJodiList.take(8).joinToString(", ")
        } else {
            prediction.jodiList.take(8).joinToString(", ")
        }
        val panasText = prediction.panneList.take(6).joinToString(", ")

        return """
            👑 *A23MAX PRO PREDICTIONS* 👑
            ═══════════════════
            📊 *Market:* ${prediction.marketName.uppercase()}
            📅 *Date:* ${prediction.date}
            ⚡ *Formula:* $formulaName
            ═══════════════════
            🎯 *SINGLE / OTC DIGITS:*
            👉 *[ $otcSpaced ]* 👈
            
            🔥 *SUPER MASTER JODIS:*
            👉 $superJodisText
            
            💎 *SPECIAL SUPPORT PANAS:*
            👉 $panasText
            ═══════════════════
            ⭐ *Confidence:* 94.8% AI Verified
            🔒 *Generated by A23MAX Pro Analytics*
        """.trimIndent()
    }

    fun shareToWhatsApp(context: Context, text: String) {
        try {
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, text)
                setPackage("com.whatsapp")
            }
            context.startActivity(intent)
        } catch (_: Exception) {
            shareToAnyApp(context, text, "Share via WhatsApp")
        }
    }

    fun shareToAnyApp(context: Context, text: String, title: String = "Share Prediction") {
        val sendIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
        }
        val shareIntent = Intent.createChooser(sendIntent, title)
        context.startActivity(shareIntent)
    }

    fun copyToClipboard(context: Context, text: String, label: String = "A23 Prediction") {
        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText(label, text)
        clipboard.setPrimaryClip(clip)
        Toast.makeText(context, "Copied to Clipboard! 📋", Toast.LENGTH_SHORT).show()
    }
}
